### ISSUE TITLE
Why `owner`+`repo`, not `repository`?

### ISSUE THREAD

**Issue by oprypin** [pozetroninc/github-action-get-latest-release#1]
Thanks for the project.

It is not very aesthetically pleasing to see [everything](https://github.com/actions/checkout#usage) use the format
```yaml
repository: foo/bar
```
except this one which uses
```yaml
owner: foo
repo: bar
```
&ndash; why?

**Comment by neil-pozetroninc** [comment]
To be honest because I didn't think of it. I'm not opposed to adding another `repository` input using that format. 

I might get around to adding it (it's lower on my list because it works as is right now) so if you want to make the change and send me a PR I'll happily review and merge it.

**Comment by oprypin** [comment]
Sorry, I will not send a PR.
BTW to accept contributions (and for other reasons) you need a LICENSE :D

**Comment by neil-pozetroninc** [comment]
Haha, right you are. I've put up an MIT license https://github.com/pozetroninc/github-action-get-latest-release/blob/master/LICENSE

Looks like for now this feature will get the old Carmack ETA of "when it's done". Thanks for the idea!

**Comment by neil-pozetroninc** [comment]
OK, it bothered me not to have this now, so I added `repository` as an option for you @oprypin. It's there in the new release.
