### ISSUE TITLE
Release description

### ISSUE THREAD

**Issue by rumpl** [pozetroninc/github-action-get-latest-release#11]
Hi, 

We are using your action to check if one of our dependencies has a new release, and if it does we open a PR that updates our dependency. One thing that we are missing that we would love to have is the release description so that we can add it to our PR, would you be ok if I created a PR to add the `description` of the release in the outputs?

Thanks

**Comment by neil-pozetroninc** [comment]
Yeah for sure! 
I try and maintain backwards compatibility and stay focused on "doing one thing right" and I think this suggestion fits within those bounds.
