### ISSUE TITLE
Default to current repo

### ISSUE THREAD

**Issue by OJFord** [pozetroninc/github-action-get-latest-release#14]
It might be good to default to the current repo (that in which the Action is running) if `owner/repo/repository` aren't given?

Since they're all optional, I initially assumed that was the behaviour (and then thought 'Error: Not Found' was referring to the action itself..) but I now realise that it's really just to allow the option of splitting `owner` & `repo` or not.

As an alternative solution/aside, perhaps it could just be `repository`, and default to current `owner` if no `/`? (Or just `owner`/`repo`, and default to current owner.)

Thanks.

**Comment by OJFord** [comment]
In case it saves anyone else a search -
```yml
with:
  repository: ${{ github.repository }}
```

**Comment by neil-pozetroninc** [comment]
I think your solution fits the "explicit is better than implicit" mantra so let's point people to this solution!

Would you like to add this an example to the README to make it easier for people to find?
