### ISSUE TITLE
error: Not found

### ISSUE THREAD

**Issue by hgjura** [pozetroninc/github-action-get-latest-release#20]
Hello 

I am trying to use this, but I am getting an error "Not Found".

I am using it like this:
- name: Get Last Release Id
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
        excludes: prerelease, draft

The repo in question has at least two releases created (manually). So I am not sure what is not able to find.

Thanks

**Comment by alsidneio** [comment]
Are you trying to pull from a private repo, it might need a github token.

**Comment by ArnoSoontjens** [comment]
Same issue here! 'token' is not an option. How can we add one?

**Comment by OS-veracardoso** [comment]
> Are you trying to pull from a private repo, it might need a github token.

What is the syntax to use a token? Thanks in advance.

**Comment by shawaj** [comment]
#27 should fix this when merged. you can see the readme there how to use the token
