### ISSUE TITLE
Latest release not on marketplace

### ISSUE THREAD

**Issue by shawaj** [pozetroninc/github-action-get-latest-release#28]
Looks like this release https://github.com/pozetroninc/github-action-get-latest-release/releases/tag/v0.6.0

Is not on the marketplace. Might need to edit it and tick the box to add to marketplace.

**Comment by neil-pozetroninc** [comment]
Thanks for this issue and for all the awesome work in the PR @shawaj!

I've merged your changes and published the new version to the marketplace just now.

**Comment by shawaj** [comment]
No problems. My pleasure
