### ISSUE TITLE
update node version

### ISSUE THREAD

**Issue by du33169** [pozetroninc/github-action-get-latest-release#31]
github shows warning when running actions:
```txt
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pozetroninc/github-action-get-latest-release@master
```

**Comment by jirkapok** [comment]
Source of the issue: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by neil-pozetroninc** [comment]
Hi all, thank you for taking the time to report this. I've just completed a round of dependency updates and this should be fixed :tada: 

https://github.com/pozetroninc/github-action-get-latest-release/blob/master/action.yaml#L33
```
  using: 'node20'
```
