### ISSUE TITLE
Draft release doesn't shown

### ISSUE THREAD

**Issue by InsonusK** [pozetroninc/github-action-get-latest-release#9]
I try to use this action to get latest draft release but it shown only latest release.

**Comment by neil-pozetroninc** [comment]
Hey @InsonusK, this is a bit of a funny one. I don't **_think_** draft releases are publicly accessible and this action doesn't use authentication so I don't *think* it's possible to retrieve draft releases.

I'd be happy to be proven wrong though!

**Comment by InsonusK** [comment]
@neil-pozetroninc 
You are right, you can't get access to draft release with out github.token of repo and using octokit.repos.listReleases.

But in your README.MD you have:
> **Additional Inputs (Optional)**
> Name | Description | Example
> --- | --- | ---
> excludes | Exclude draft or pre-release versions. | "prerelease, **draft**"

What do you mean in **draft**?

**Comment by neil-pozetroninc** [comment]
Yeah, that's going to cause some confusion. Sorry, I'll update the README. 

If the action used authentication or the API changed that would exclude drafts. Right now it's a noop.
